import type { Metadata } from "next";
import { Elsie, Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

const elsie = Elsie({
  variable: "--font-display",
  subsets: ["latin"],
  weight: ["400", "900"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${elsie.variable} antialiased`}>
        <div className="site-frame">
          <div className="site-frame__border site-frame__border--left" aria-hidden="true" />
          <div className="site-frame__border site-frame__border--right" aria-hidden="true" />
          <div className="site-frame__content">{children}</div>
        </div>
      </body>
    </html>
  );
}
